### ISSUE TITLE
TextMate is bundled and turned on by default, update README

### ISSUE THREAD

**Issue by CrazyPython** [hjson/textmate-hjson#1]

**Comment by laktak** [comment]
According to https://www.jetbrains.com/help/idea/2016.2/textmate.html it is not included.

**Comment by TerrorBite** [comment]
This issue appears to have been created when JetBrains was just migrating to including TextMate by default.

Now 9 years later it has been bundled for a long time, and this is clearly stated on the very same URL you posted:

> This functionality relies on the [TextMate Bundles](https://plugins.jetbrains.com/plugin/7221) plugin, which is bundled and enabled in IntelliJ IDEA by default.

#10 is a duplicate of this issue.
