### ISSUE TITLE
Almost no syntax highlighting

### ISSUE THREAD

**Issue by CrazyPython** [hjson/textmate-hjson#3]
Please make keys, numbers, and values different colors.

**Comment by laktak** [comment]
This bundle only defines the syntax. The colors are handled by the IntelliJ bundle. Try changing the mapping (see readme).

**Comment by CrazyPython** [comment]
@laktak keys and values are the same color. Darcula done and done.

**Comment by laktak** [comment]
I found a hint that you can import a TextMate bundle with schemes and updated the readme.

**Comment by PlkMarudny** [comment]
In not a single theme brackets have different colors than keys and string values, is this possible?
