### ISSUE TITLE
Comment highlighting

### ISSUE THREAD

**Issue by Tereci** [hjson/textmate-hjson#4]
Hi, 
I noticed, that the plugin highlights any text after :// as a comment no matter what it's surrounded by. So e.g. if I have a line like
`"jdbc_url": "jdbc:gdc:datawarehouse://{params.hostname}}/datawarehouse/instances/xzy"`
everything after //{ looks like a comment. When I parse it, it is not interpreted as a comment as well as when I try to reproduce this issue on the official HJSON site https://hjson.org/try.html it doesn't interpret or highlight such cases as comments which leads me to believe it's an error in this plugin.
The same goes for :# and :*/

**Comment by laktak** [comment]
Thanks - this should be fixed by #5

**Comment by laktak** [comment]
Please test with the update.

**Comment by Tereci** [comment]
Hi, I tried the update and it appears to be working, thanks! :)
