### ISSUE TITLE
Requires trailing comma or whitespace after last subobject

### ISSUE THREAD

**Issue by rulatir** [hjson/textmate-hjson#7]
Steps to reproduce:
1) Create a .hjson file with the following content and open it after installing textmate-hjson in PHPStorm 2018.2:

```
{
    subobject: {}
}
```

Expected behavior:
The last closing brace should not have syntax error highlight.

Actual behavior:
The last closing brace has syntax error highlight.

Additional observations:

1) If comma or whitespace is added after the subobject's closing brace, the syntax error highlight goes away. Same if whitespace is added before the end of the line that contains the subobject's closing brace. Neither is a good workaround because the comma is ugly and trailing whitespaces can be stripped by editor.

2) This happens whenever the **last** subobject of an object is not terminated by comma or whitespace after the closing brace (but on the same line), even if that subobject is not the last property. It therefore happens i this case:

```
{
    am_I_an_object: { answer: "yes" }
    am_I_one_too: false
}
```

But not in this one (note the comma):

```
{
    am_I_an_object: { answer: "yes" },
    am_I_one_too: false
}
```

**Comment by laktak** [comment]
Sorry, this project is EOL, see https://hjson.org

**Comment by dqsully** [comment]
Thanks for reporting this @rulatir. I just pushed some new changes that should fix this bug among others. Could you test it out to see if everything works for you now?

**Comment by dqsully** [comment]
This appears to be fixed so I'm closing this issue.
