### ISSUE TITLE
Errors Parsing HJSON (IntelliJ)

### ISSUE THREAD

**Issue by noblemaster** [hjson/textmate-hjson#8]
I getting several errors for the following JSON. I am using the latest version of IntelliJ, TextMate and HJSON:
```
schema: [
  { id: 7
    spec: {
      comp: {
        any: true
      }
      wrong-color: {
        some: "thing"
      }
    }
  }
]
```

**Error List**:
- 3x curly braces '}' are highlighed in red
- 1x rectangular ']' brace in red
- the "wrong-color" part is wrongly colored.

**Editor Screenshot**:
![2019-03-03 hjson formatter - problem](https://user-images.githubusercontent.com/2363626/53694265-aa96d300-3def-11e9-9840-db834d872e4c.png)

**Comment by dqsully** [comment]
Sorry for the late reply. Hjson's implicit root object syntax has been deprecated. Try this instead:
```
{
  schema: [
    { id: 7
      spec: {
        comp: {
          any: true
        }
        wrong-color: {
          some: "thing"
        }
      }
    }
  ]
}
```

**Comment by noblemaster** [comment]
Adding the root object removes 1 error. Other errors are still there. Also, I have tried my original HJSON here: https://hjson.org/try.html It works without showing any errors at all. 

I wasn't aware the root braces are deprecated? Based on https://hjson.org/syntax.html it's still pending (end of the page)!?

**Comment by dqsully** [comment]
I don't know about the current status of the RFC, but that page does explain that root braces are obsolete:
> While Hjson allows you to omit {} for the root object, this feature should no longer be used.

~Could you upload a screenshot of the errors you still see in IntelliJ?~ Never mind, I installed IntelliJ on my system and I see the same issues.

**Comment by dqsully** [comment]
This issue seems to be caused by a difference in how VS Code handles TextMate grammars and how IntelliJ does it. Until I pinpoint the issue, if you decide keep using Hjson in IntelliJ, you can just put a comma after every closing brace of an object property like so:

```
{
  schema: [
    { id: 7
      spec: {
        comp: {
          any: true
        },
        wrong-color: {
          some: "thing"
        },
      },
    }
  ]
}
```

**Comment by noblemaster** [comment]
I am aware that putting a comma and the root braces back into the HJSON text will fix the IntelliJ syntax errors. However, that somewhat defeats the purpose of HJSON and ends just up with regular JSON instead...

I looked at the "Hjson.tmLanguage", but it's little bit over my head to attempt to fix it myself. I am not in a rush. I don't mind dealing with syntax errors now, given that it will hopefully be fixed in the future. Just thought I let someone know :)

I don't know about the status of the RFC either? Although the page discourages from using root braces, they are stated in the RFC. Ditto above, would that not go with the meaning of "Human" JSON to allow to obit them, to make the document more readable? I can't see why that would not be possible from a technical point of view, besides probably being harder to parse?

**Comment by dqsully** [comment]
Yeah, explicit root braces make parsing quite a bit simpler. Thanks for submitting this bug, you definitely let the right person know 🙂.

**Comment by noblemaster** [comment]
I found a solution: telling IntelliJ to parse the file as `*.xaml` via Settings->File Types does produce correct formatting. That was unexpected.
